name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node: [18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
      - run: yarn
      - run: yarn run test

      - name: Generate tag
        id: tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: lucapinheiro/rocketseat-ci-api:${{ steps.tag.outputs.sha }},lucapinheiro/rocketseat-ci-api:latest
        
      # - name: Build docker image
      #   run : docker build -t lucapinheiro/rocketseat-ci-api:${{ steps.tag.outputs.sha }} .

      # - name: Push docker image
      #   run: docker push lucapinheiro/rocketseat-ci-api:${{ steps.tag.outputs.sha }}



          