name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - run: yarn
      - run: yarn run test

      - name: Generate tag
        id: tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::790856957430:role/ecr-role
          aws-region: us-east-2

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2




      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and Push
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: lucapinheiro/rocketseat-ci-api:${{ steps.tag.outputs.sha }},lucapinheiro/rocketseat-ci-api:latest
        
      # - name: Build docker image
      #   run : docker build -t lucapinheiro/rocketseat-ci-api:${{ steps.tag.outputs.sha }} .

      # - name: Push docker image
      #   run: docker push lucapinheiro/rocketseat-ci-api:${{ steps.tag.outputs.sha }}



          